### PR TITLE
fix stats

### PR DESCRIPTION
**Pull request by queenkoopa8500**

### CODE REVIEW

**Comment by AgentXLP** [comment]
I'm gonna fix my own stats.

**Comment by AgentXLP** [comment]
Thank you though I didn't notice

**Comment by queenkoopa8500** [comment]
> Thank you though I didn't notice

no problem

**Comment by queenkoopa8500** [comment]
> Thank you though I didn't notice

Hey Agent, your github profile has the website url as: `https://agent-11.github.io` still. You gotta change it to `https://agentxlp.github.io` (just pointing this out)

**Comment by AgentXLP** [comment]
Okay, thank you!

**Pull request closed without merging**
